___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [38]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [39]:
import numpy as np

print(np.__version__)
np.show_config()


1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alyona/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alyona/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alyona/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alyona/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alyona/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alyona/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alyona/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alyona/anaconda3\\Library\\include']


Створити вектор з 10 елементів, заповнений одиницями:

In [40]:
import numpy as np

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [41]:
import numpy as np

np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [43]:
import numpy as np

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [46]:
import numpy as np

a = np.random.randint(20, size=20)
print(a)
np.nonzero(a)

[19 10 12 16  2  0  3  0  8  6 10 10  7  8  3  5 11  2  0 11]


(array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19],
       dtype=int64),)

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [47]:
import numpy as np

print('Середнє значення:', np.mean(a))
print('Медіана:', np.median(a))
print('Стандартне відхилення:', np.std(a))

Середнє значення: 7.15
Медіана: 7.5
Стандартне відхилення: 5.217997700267795


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [48]:
import numpy as np

M1 = np.random.random((4, 2))
M2 = np.random.random((2, 2))
MM = np.dot(M1, M2)
print(M1)
print()
print(M2)
print()
print(MM)

[[0.9481893  0.58151486]
 [0.54808577 0.82566694]
 [0.73374328 0.16282782]
 [0.90940108 0.85790311]]

[[0.36228392 0.37971142]
 [0.0108849  0.62605939]]

[[0.34984347 0.72410115]
 [0.20754996 0.72503097]
 [0.26759576 0.38055059]
 [0.33879958 0.88240828]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [49]:
import numpy as np

MM1 = MM.flatten()
i_max = np.argmax(MM1)
MM1[i_max] = 0
print(MM1)
print('Мінімальне значення:', np.min(MM))
print('Максимальне значення:', np.max(MM))

[0.34984347 0.72410115 0.20754996 0.72503097 0.26759576 0.38055059
 0.33879958 0.        ]
Мінімальне значення: 0.20754996378700497
Максимальне значення: 0.8824082777119882


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [50]:
np.correlate(MM[0], MM[1])

array([0.59760576])

In [51]:
np.correlate(MM[0], MM[2])

array([0.36917375])

In [52]:
np.correlate(MM[0], MM[3])

array([0.75747967])

Дано матрицю. Знайти ранг матриці:

In [53]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [54]:
det = np.linalg.det(a)
print(det)

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [55]:
eig = np.linalg.eig(a)
print(eig)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
       -4.56760167-3.20389947j]), array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
        -0.31386258+0.47450898j],
       [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
        -0.07049527-0.4090732j ],
       [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
         0.7099444 -0.j        ]]))


Знайдіть число, що найчастіше зустрічається в масиві:

### Варіант 1

In [74]:
a = np.random.randint(0,10,50)
print(a)
unique, counts = np.unique(a, return_counts=True)
c = unique[np.argmax(counts)]
print()
print(np.asarray((unique, counts)).T)
print()
print('Число, що найчастіше зустрічається в масиві:', c)

[9 8 4 0 4 6 1 9 2 6 8 3 1 2 5 6 0 3 6 4 1 1 4 9 1 9 5 4 5 5 1 2 4 1 8 5 7
 0 7 7 5 1 5 1 7 4 1 2 7 7]

[[ 0  3]
 [ 1 10]
 [ 2  4]
 [ 3  2]
 [ 4  7]
 [ 5  7]
 [ 6  4]
 [ 7  6]
 [ 8  3]
 [ 9  4]]

Число, що найчастіше зустрічається в масиві: 1


### Варіант 2

In [82]:
from scipy import stats

a = np.random.randint(0,10,50)
print(a)
mode_info = stats.mode(a)
print('Число, що найчастіше зустрічається в масиві:', mode_info[0])

[1 7 8 8 1 2 1 0 6 9 4 9 4 2 2 9 6 0 0 0 1 4 7 4 5 1 4 4 2 8 5 7 7 9 4 3 3
 1 2 2 4 2 1 7 0 7 4 4 6 0]
Число, що найчастіше зустрічається в масиві: [4]


### Виведіть лише парні числа, що діляться на 5:

In [58]:
a = np.random.randint(0,10,50)
print(a)
a[(a % 2 == 0) & (a % 5 == 0) & (a > 0)]

[7 2 1 3 5 5 5 4 7 1 5 1 8 0 2 2 1 1 6 9 8 9 6 1 2 4 9 9 0 0 4 3 2 5 7 7 2
 5 2 1 9 0 3 0 5 7 4 2 8 6]


array([], dtype=int32)

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [64]:
a = np.array([[2, 5], [1, -10]])
b = np.array([1, 3])
x = np.linalg.solve(a,b)
print(x)

[ 1.  -0.2]
